[versions]
loom = "1.17-SNAPSHOT"
kotlin = "2.4.10"

devauth = "1.2.1"

fabric-loader = "0.19.3"
fabric-language-kotlin = "1.13.13+kotlin.2.4.10"

fabric-api-26-1 = "0.155.2+26.1.2"
fabric-api-26-2 = "0.158.0+26.2"

modmenu-26-1 = "3rsoV1bk"
modmenu-26-2 = "njXb639R"

caxton-26-1 = "paJOxYlD"
caxton-26-2 = "wVI9Rvrv"

entityculling-26-1 = "DhN0G638"
entityculling-26-2 = "iiF6U3Ne"

exordium-26-1 = "IK5p5vrB"
exordium-26-2 = "IK5p5vrB"

iris-26-1 = "YEGDGnJM"
iris-26-2 = "oaD6KQls"

skyblock-api = "4.2.19"
classgraph = "4.8.184"
autoupdate = "1.3.1"
kommand = "1.0.2"

snowbird-26-1 = "016+26.1"
snowbird-26-2 = "016+26.2"

cascade-26-1 = "036+26.1"
cascade-26-2 = "036+26.2"

hypixel-modapi = "1.0.1"
hypixel-modapi-fabric = "1.0.1+build.1+mc1.21"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }

fabric-api-26-1 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-26-1" }
fabric-api-26-2 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-26-2" }

snowbird-26-1 = { module = "foo.starred:snowbird", version.ref = "snowbird-26-1" }
snowbird-26-2 = { module = "foo.starred:snowbird", version.ref = "snowbird-26-2" }

cascade-26-1 = { module = "foo.starred:cascade", version.ref = "cascade-26-1" }
cascade-26-2 = { module = "foo.starred:cascade", version.ref = "cascade-26-2" }

modmenu-26-1 = { module = "maven.modrinth:modmenu", version.ref = "modmenu-26-1" }
modmenu-26-2 = { module = "maven.modrinth:modmenu", version.ref = "modmenu-26-2" }

caxton-26-1 = { module = "maven.modrinth:caxton", version.ref = "caxton-26-1" }
caxton-26-2 = { module = "maven.modrinth:caxton", version.ref = "caxton-26-2" }

entityculling-26-1 = { module = "maven.modrinth:entityculling", version.ref = "entityculling-26-1" }
entityculling-26-2 = { module = "maven.modrinth:entityculling", version.ref = "entityculling-26-2" }

exordium-26-1 = { module = "maven.modrinth:exordium", version.ref = "exordium-26-1" }
exordium-26-2 = { module = "maven.modrinth:exordium", version.ref = "exordium-26-2" }

iris-26-1 = { module = "maven.modrinth:iris", version.ref = "iris-26-1" }
iris-26-2 = { module = "maven.modrinth:iris", version.ref = "iris-26-2" }

skyblock-api = { module = "tech.thatgravyboat:skyblock-api", version.ref = "skyblock-api" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
autoupdate = { module = "moe.nea:libautoupdate", version.ref = "autoupdate" }
kommand = { module = "foo.starred:kommand", version.ref = "kommand" }
hypixel-modapi = { module = "net.hypixel:mod-api", version.ref = "hypixel-modapi" }
hypixel-modapi-fabric = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixel-modapi-fabric" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
